### PR TITLE
[CI] Ruby 2.3 and 2.5

### PR DESCRIPTION
**Pull request by nicolasleger**

### CODE REVIEW

**Comment by ankane** [comment]
Hey @nicolasleger, can you explain your thinking behind this PR?

**Comment by nicolasleger** [comment]
Hey @ankane , ensure the gem tests pass on current maintained Ruby versions.

**Comment by ankane** [comment]
Thanks @nicolasleger 👍 Since Ruby does a great job at maintaining backward compatibility, I don't think testing multiple versions adds much benefit. I also want to be mindful of Travis CI resources (and keep the test suite fast).

**Comment by nicolasleger** [comment]
I understand but there can be some incompatible changes between native Ruby 2.x or dependencies like `activesupport `https://github.com/rails/rails/blob/master/.travis.yml tested on `2.4.3` and `2.5.0`.

**Comment by ankane** [comment]
It's definitely possible, but Groupdate hasn't had an issues with it. Certainly happy to reconsider if version-specific issues start popping up.

**Pull request closed without merging**
