### PR TITLE
Group by time range

### LINKED ISSUE #147: [Feature] It would be nice to have grouping by specific time range

### PR DESCRIPTION
**Pull request by lesniakania**
Fixes #147 

I know that one test is failing, but for now, I have no idea why.

### CODE REVIEW

**Comment by ankane** [comment]
Hey @lesniakania, thanks for this PR as well!

Can you explain it a bit more and how it differs from the current options? Also, please separate it from the `database_time_zone` feature.

**Comment by lesniakania** [comment]
It adds grouping by specific time range. You choose end date, range length and ranges count and it generates time series based on that and lets you calculate measurements grouped by this periods.

I think this test explains it the most:

```ruby
  def test_group_by_time_range_relation
    create_user("2014-01-07")
    create_user("2014-01-14")
    create_user("2014-02-04")
    expected = {
      Date.parse("2014-01-06") => 2,
      Date.parse("2014-01-20") => 0,
      Date.parse("2014-02-03") => 1
    }
    assert_equal expected, User.group_by_time_range(:created_at,
      series: true,
      time_range_end: Date.parse("2014-02-17"), time_range_length: 2.weeks, time_ranges_count: 3).count
  end
```

It's different from already existing groupings because you can choose to dynamically group not only by day or week etc but any given time range.

**Comment by lesniakania** [comment]
@ankane I started extracting time zone changes and I can continue, but if timezone PR gets accepted the changes I'm reverting now, need to be done again, so just wondering if it makes sense - maybe we can just wait with this, what do you think?

**Comment by ankane** [comment]
I think I understand - this is similar to #23?

I'm happy to wait until the `database_time_zone` PR is resolved. It'd be great if you could rebase once that happens.

**Comment by lesniakania** [comment]
Yes, it would solve the issue, you can pass `10.minutes` as `time_range_length`.
And sure, I will rebase after PR is resolved :)

**Comment by ankane** [comment]
Cleaning up PRs. Feel free to address the above and reopen.

**Pull request closed without merging**
