### PR TITLE
Minor update to help file to explain default values for 0 counts

### PR DESCRIPTION
**Pull request by Carpela**
Really basic one. I think this covers the current functionality. It might need to be adjusted to cover the exact functionality that's been added in v 2.5.1 for default values. 
e.g. I tried default_value:0 and that didn't work, but default_value:true gave me the 0 values I needed.

### CODE REVIEW

**Comment by codesnik** [comment]
:+1:
this feature isn't obvious from README and is a big selling point for using that gem

**Comment by ankane** [comment]
Hi Keiran, thanks for the pull request!  However, I'm not sure I understand it. `default_value` is only needed if you wan't something other than 0.

**Comment by Carpela** [comment]
Hi ankane,

The point is that the hash that's returned doesn't include the 0 values. 
Now if you're creating a chart where 0 values are relevant, having them missing is a real pain as you have to manually add them back in.

What I was doing was just trying to make sure they appeared. 

Am I misunderstanding something here?

Keiran

**Comment by ankane** [comment]
Can you run the following commands in the Rails console and paste the output? (substitute your model)

```ruby
Groupdate::VERSION
YourModel.group_by_year(:created_at, last: 10).count
```

**Comment by mnort9** [comment]
+1. I've tried providing a `default_value` of 0 and true. Neither give back data with 0 values, so I need to manually add them in.

**Comment by mnort9** [comment]
I just realized my use case is slightly different. The series is defined by the data points created_at 'start_date' and 'end_date'. My base query extends the range of the 'end_date', where data points don't exist yet, so I assumed I would get 0's for all future dates within the query. 

Though, this may be outside the scope of the gem....

**Comment by ankane** [comment]
There's now a section on default values. https://github.com/ankane/groupdate#series

**Pull request closed without merging**
