### PR TITLE
Simplify Postgres queries for default settings

### PR DESCRIPTION
**Pull request by codesnik**
queries generated by default are just too bulky and hard to read (formula is complex and repeated twice, in select and in a group clause). 
I've tried to omit unneeded math on default values, for postgres. I hope, this doesn't make code more complex than it should be. What do you think?

### CODE REVIEW

**Comment by codesnik** [comment]
on the second thought, maybe I broke things for 'Etc/UTC' timezone, and tests just not catch that problem. I'll check again

**Comment by ankane** [comment]
Thanks @codesnik. It does make the executed queries simpler to read, but adds complexity to the code. Overall, I don't see too much value from merging, so going to close this.

**Comment by codesnik** [comment]
that's sad. Monstrous queries in development.log could be repulsive for gem
adopters, when they do not use timezone change or some other features.

**Comment by ankane** [comment]
I'm not totally convinced it'll deter new users from the gem, but I see your point about it being nicer to read.  I'm happy to merge.  Can you change `ajust` -> `adjust`?

**Comment by codesnik** [comment]
will do in in a couple days.

**Comment by ankane** [comment]
It would also be nice to do this for MySQL, but we can start with only Postgres.

**Comment by codesnik** [comment]
afair I tried to do it for MySQL, something prevented me from doing that.
I'll look into that too.

**Comment by ankane** [comment]
Cleaning up PRs. Feel free to address the above and reopen.

**Pull request closed without merging**
